[deps]
AugmentedPoissonBoltzmann = "d8b18f01-5396-498d-b34d-247825c18ff1"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[sources]
AugmentedPoissonBoltzmann = {path = "/home/fuhrmann/Wias/work/julia/dev/AugmentedPoissonBoltzmann"}
